# Generated by Django 3.0.1 on 2019-12-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='store',
            table='stored_key_value',
        ),
    ]
