# Generated by Django 3.0.1 on 2019-12-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191224_1634'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
    ]
