# Generated by Django 3.0.1 on 2019-12-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_store_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='posting_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
