# Generated by Django 3.0.1 on 2019-12-25 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191225_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
